version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogSqlServer=Server=sqlserver;Database=CatalogDb;User Id=sa;Password=<MyStrongP@ssw0rd>;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq
      - Consul__ConsulAddress=http://consul:8500
      - Consul__ServiceAddress=http://catalog.api
    ports:
      - "80"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  cart.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__DiscountGrpcUrl=discount.grpc
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq
      - Consul__ConsulAddress=http://consul:8500
      - Consul__ServiceAddress=http://cart.api
    ports:
      - "80"

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DiscountSqlServer=Server=sqlserver;Database=DiscountDb;User Id=sa;Password=<MyStrongP@ssw0rd>;
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    environment:
      - SA_PASSWORD=<MyStrongP@ssw0rd>
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
  
  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
      - "5341:5341"
    volumes:
      - seq-data:/data

  consul:
    ports:
      - "8500:8500"
    volumes:
      - consul-data:/consul/data

  gateway.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "443"

volumes:
  sqlserver-data:
    external: false

  seq-data:
    external: false

  consul-data:
    external: false