version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - microstore

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile
    networks:
      - microstore

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - microstore

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    networks:
      - microstore

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - microstore

  seq:
    image: datalust/seq
    networks:
    - microstore

  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: ApiGateways/Gateway.WebApi/Dockerfile

networks:
  microstore:
    name: microstore-network
