version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - microstore

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - microstore

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.Api/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    networks:
      - microstore

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    depends_on:
      - sqlserver
    networks:
      - microstore

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    networks:
      - microstore

  redis:
    image: redis:alpine
    restart: always
    networks:
      - microstore
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - microstore

  seq:
    image: datalust/seq
    restart: always
    networks:
      - microstore

  consul:
    image: consul
    restart: always
    networks:
      - microstore

  gateway.webapi:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: ApiGateways/Gateway.WebApi/Dockerfile
    depends_on:
      - catalog.api
      - cart.api
      - ordering.api
    networks:
      - microstore

networks:
  microstore:
    name: microstore-network